services:
  - type: web
    name: fraudshield-ml
    env: docker
    rootDir: ./ml
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /health

  - type: web
    name: fraudshield-app
    env: docker
    rootDir: .
    dockerfilePath: ./Dockerfile
    plan: free
    autoDeploy: true
    healthCheckPath: /pages/index.html
